// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    'Icon:ic:baselineArrowRightAlt': typeof import('~icons/ic/baseline-arrow-right-alt')['default']
    'IconBi:exclamationCircleFill': typeof import('~icons/bi/exclamation-circle-fill')['default']
    'IconClarity:timesCircleSolid': typeof import('~icons/clarity/times-circle-solid')['default']
    'IconClarity:timesLine': typeof import('~icons/clarity/times-line')['default']
    'IconFaSolid:ellipsisV': typeof import('~icons/fa-solid/ellipsis-v')['default']
    'IconIc:baselineContentCopy': typeof import('~icons/ic/baseline-content-copy')['default']
    'IconLa:language': typeof import('~icons/la/language')['default']
    'IconMdi:alert': typeof import('~icons/mdi/alert')['default']
    'IconMdi:arrowDownDropCircleOutline': typeof import('~icons/mdi/arrow-down-drop-circle-outline')['default']
    'IconMdi:ArrowDownDropCircleOutline': typeof import('~icons/mdi/-arrow-down-drop-circle-outline')['default']
    'IconMdi:arrowUpDropCircleOutline': typeof import('~icons/mdi/arrow-up-drop-circle-outline')['default']
    'IconMdi:ArrowUpDropCircleOutline': typeof import('~icons/mdi/-arrow-up-drop-circle-outline')['default']
    'IconMdi:burgerAdd': typeof import('~icons/mdi/burger-add')['default']
    'IconMdi:checkboxMarkedCircle': typeof import('~icons/mdi/checkbox-marked-circle')['default']
    'IconMdi:checkCircle': typeof import('~icons/mdi/check-circle')['default']
    'IconMdi:checkCircleOutline': typeof import('~icons/mdi/check-circle-outline')['default']
    'IconMdi:closeOutline': typeof import('~icons/mdi/close-outline')['default']
    'IconMdi:create': typeof import('~icons/mdi/create')['default']
    'IconMdi:createOutline': typeof import('~icons/mdi/create-outline')['default']
    'IconMdi:deleteOutline': typeof import('~icons/mdi/delete-outline')['default']
    'IconMdi:githubFace': typeof import('~icons/mdi/github-face')['default']
    'IconMdi:loading': typeof import('~icons/mdi/loading')['default']
    'IconMdi:messageTextOutline': typeof import('~icons/mdi/message-text-outline')['default']
    'IconMdi:minus': typeof import('~icons/mdi/minus')['default']
    'IconMdi:pencilBoxOutline': typeof import('~icons/mdi/pencil-box-outline')['default']
    'IconMdi:pencilCircleOutline': typeof import('~icons/mdi/pencil-circle-outline')['default']
    'IconMdi:plus': typeof import('~icons/mdi/plus')['default']
    'IconMdi:plusCircleOutline': typeof import('~icons/mdi/plus-circle-outline')['default']
    'IconMdi:refresh': typeof import('~icons/mdi/refresh')['default']
    'IconMdi:trashOutline': typeof import('~icons/mdi/trash-outline')['default']
    'IconSimpleIcons:nuxtdotjs': typeof import('~icons/simple-icons/nuxtdotjs')['default']
    'IconUil:angleDown': typeof import('~icons/uil/angle-down')['default']
    'IconUil:bars': typeof import('~icons/uil/bars')['default']
    'IconUil:clock': typeof import('~icons/uil/clock')['default']
    'IconUil:laptop': typeof import('~icons/uil/laptop')['default']
    'IconUil:moon': typeof import('~icons/uil/moon')['default']
    'IconUil:sun': typeof import('~icons/uil/sun')['default']
    'IconUil:times': typeof import('~icons/uil/times')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
